/****************************************START FIRST FONT******************************************************/
.mfp-counter, 
.mfp-title, 
#wp-calendar caption, 
#wp-calendar thead th, 
.widget_search input[type="submit"], 
.comment-respond input[type="submit"], 
.comment-reply-link,
.nicdark_btn,
.nicdark_btn_icon,
.ui-datepicker-title,
.ui-datepicker-calendar thead,
h1,
h2,
h3,
h4,
h5,
h6,
input[type="text"],
textarea,
select,
a.title,
span.title,
small.title,
input[type="submit"],
.product .onsale,
.woocommerce-pagination a,
.woocommerce-pagination span,
.woocommerce-pagination span.current,
.products li .add_to_cart_button, 
.products li .product_type_variable, 
.products li.outofstock a.button, 
.products li.product-type-external a.button, 
.products li.product-type-grouped a.button,
.quantity .minus, 
.quantity .plus, 
.quantity .qty,
button.single_add_to_cart_button,
.woocommerce-tabs li a,
.woocommerce .comment-reply-title,
.woocommerce table.shop_table th,
.woocommerce-page table.shop_table th,
.cart_totals h2,
.shipping_calculator h2 a,
.shipping_calculator button,
#customer_details .col-2 h3,
.woocommerce .addresses a,
.widget.woocommerce h2,
.widget.widget_shopping_cart .widget_shopping_cart_content p.buttons a.button, 
.woocommerce .widget_price_filter .price_slider_amount .price_label,
.woocommerce .widget_price_filter .button,
.wc-backward,
#ship-to-different-address label
{ font-family: <?php echo $redux_demo['first_font']['font-family']; ?>; }

.tp-arr-titleholder,
.woocommerce-billing-fields h3
{ font-family: <?php echo $redux_demo['first_font']['font-family']; ?> !important; }

/****************************************START SECOND FONT******************************************************/
.widget,
.widget_search input[type="text"],
.comment-reply-title,
.comment-author,
.tinynav,
.menu  a,
.nicdark_archive1_content,
.ui-tooltip,
h1.subtitle,
h2.subtitle,
h3.subtitle,
h4.subtitle,
h5.subtitle,
h6.subtitle,
input[type="text"].subtitle,
textarea.subtitle,
select.subtitle,
span.subtitle,
p,
html,
a,
input[type="text"],
input[type="email"],
input[type="url"],
input[type="tel"],
input[type="number"],
input[type="date"],
textarea,
.wpcf7-select,
.widget_archive select,
.widget_categories select,
.widget_text select,
.wpb_heading,
div.wpcf7-validation-errors,
div.wpcf7-mail-sent-ng,
div.wpcf7-spam-blocked,
div.wpcf7-mail-sent-ok,
.wpcf7-not-valid-tip,
.woocommerce-account .woocommerce h2, 
.woocommerce-checkout .woocommerce h2,
.product .related h2,
.upsells.products h2,
.product h1,
.variations_form table td select,
.shipping_calculator select, 
.shipping_calculator input[type="text"],
.chosen-container-single .chosen-search input[type=text],
#order_review_heading,
.woocommerce form h3
{ font-family: <?php echo $redux_demo['second_font']['font-family']; ?>; }

.nicdark_btn.subtitle,
.nicdark_btn_icon.subtitle
{ font-family: <?php echo $redux_demo['second_font']['font-family']; ?> !important; }


/****************************************START THIRD FONT******************************************************/
h1.signature,
h2.signature,
h3.signature,
h4.signature,
h5.signature,
h6.signature,
span.signature
{ font-family: <?php echo $redux_demo['third_font']['font-family']; ?>; }